2022-02-14 16:32:32,150 remote_connection.py[line:117]INFO - Could not connect to port 4723 on host 127.0.0.1
2022-02-14 16:32:32,150 remote_connection.py[line:136]INFO - Could not get IP address for host: 127.0.0.1
2022-02-14 16:32:34,194 connectionpool.py[line:811]WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025BA5A7D288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2022-02-14 16:32:36,236 connectionpool.py[line:811]WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025BA5A7DAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2022-02-14 16:32:38,266 connectionpool.py[line:811]WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025BA5AA2448>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
